### ISSUE TITLE
Server side Grid Memory Usage Questions

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#115] opened 2020-04-17 13:37 UTC
Hi, 

We have an use case in server side blazor where we use the grid for a large dataset,  we noticed that the memory foot print is high and it does not go down long after the circuit is disconnected.

I forked the demo repo and made the grid (Server side blazor:  Datagrids -> Templates) manage large dataset, switching between this grid and others,  you can observe the memory issue I just described. 

Here is the link to test repo: [https://github.com/goldmannyc/Blazor.git](url)

thx

**Comment by outsidergiant** [comment] 2020-04-23 07:52
Hello @goldmannyc ,

Thank you for your test project. Such issues are quite complicated, and we need additional time for research. We will reply to you once we have any news.

**Comment by goldmannyc** [comment] 2020-04-23 14:36
Thanks for the update,  let us know if you need more information.

**Comment by outsidergiant** [comment] 2020-04-23 16:33
We've done some research and see the issue. We are currently working and will work on improving performance and memory usage of our components. The issue you discovered is quite complex and cannot be resolved in a day or two. We will apply solutions to improve the current situation with memory usage step by step until the issue is gone.

**Comment by goldmannyc** [comment] 2020-05-13 19:53
This is a show stopper for us at the moment,  Is this unusual large memory foot print related to Blazor server side architecture?

**Comment by outsidergiant** [comment] 2020-05-14 16:28
Hi, there is something that we can do from our side and we will improve it with our updates but there are some limitations from the Blazor Server platform and the Garbage Collector. I recorded a video to demonstrate the memory usage without our components. A sample project is also attached.
[BlazorServer.zip](https://github.com/DevExpress/Blazor/files/4629646/BlazorServer.zip)
[BlazorServer.zip](https://github.com/DevExpress/Blazor/files/4629650/BlazorServer.zip)

**Comment by zabelin-vladimir** [comment] 2020-10-02 15:18
Hello @goldmannyc

Soon, we will start to address technical requests only in our Support Center.
So, if you still need our assistance with this issue, please create a new ticket in our [Support Center](https://www.devexpress.com/ask). We will be happy to help you with this and any other questions regarding our Blazor components.

**Comment by zabelin-vladimir** [comment] 2020-10-06 08:11
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova

**Closed by zabelin-vladimir** 2020-10-06 08:11 UTC
Labels: invalid
