### ISSUE TITLE
Grid flickers in virtual scrolling mode

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#155] opened 2020-07-17 09:56 UTC
Hi!

I already opened a [similar issue](https://github.com/DevExpress/Blazor/issues/55) some time ago, which got solved. Nonetheless there is still a flicker when I change between pages in virtual scrolling mode. Almost as if it the page is loaded and displayed two times in a short time, first at the wrong position, then again at the correct position.

Example GIF:
![ScreenCapture_17 07 2020-11 42 17](https://user-images.githubusercontent.com/8930481/87774076-5e9dd000-c824-11ea-89f5-9e5c8755a4c2.gif)

Example Solution: [BlazorApp1.zip](https://github.com/DevExpress/Blazor/files/4937008/BlazorApp1.zip)

Can you look into this?

Thanks!

**Comment by zabelin-vladimir** [comment] 2020-07-20 10:38
Hello @rysep2 

Thank you for your report. We will process this issue in the context of the following ticket in our support center: [T915688](https://supportcenter.devexpress.com/ticket/details/t915688).

**Comment by zabelin-vladimir** [comment] 2020-10-02 15:18
Hello @rysep2 

We are going to address technical requests only in our [Support Center](https://www.devexpress.com/ask). 
So, I recommend you add the [mentioned ticket](https://supportcenter.devexpress.com/ticket/details/t915688/datagrid-for-blazor-the-flickering-effect-is-reproduced-when-scrolling-in-virtual) to your Favorites to get a notification when we update it.

**Comment by zabelin-vladimir** [comment] 2020-10-06 08:10
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova

**Closed by zabelin-vladimir** 2020-10-06 08:10 UTC
Labels: bug
