### ISSUE TITLE
Problem with Column Types and Filter Row

### ISSUE THREAD

**Issue by DanielReif** [DevExpress/Blazor#87] opened 2020-01-29 15:01 UTC
Hey,

i have some issues with the the new elements. I know they are in beta, but i hope it helps when i show you the errors.

Filter Row:
Your demo - Dropdowns for OrderDate/Ship Region/Order Status in Firefox (v60.6.1esr - 64-Bit)  don't open. In chrome it works.

Column Types:
Your demo - class `text-left/right/center` sometimes multiple occurs in the class tag but i cant reproduce when this happens.
![image](https://user-images.githubusercontent.com/36186128/73367335-b9ac2c80-42af-11ea-9ec7-1fd182cc4baa.png) 

Own Project -  `TextAlignment="DataGridTextAlign.Center"` dont work for `DxDataGridCheckBoxColumn`

![image](https://user-images.githubusercontent.com/36186128/73368042-a352a080-42b0-11ea-923f-4c6769aa1626.png)

![image](https://user-images.githubusercontent.com/36186128/73367988-8c13b300-42b0-11ea-907d-2b8fc0bbc6f1.png)

**Comment by outsidergiant** [comment] 2020-01-30 15:01
Hello Daniel,

Thank you for contacting us!

> *Your demo - Dropdowns for OrderDate/Ship Region/Order Status in Firefox (v60.6.1esr - 64-Bit) don't open. In chrome it works.*

I suggest that you update to the latest version of the Firefox browser. See the https://github.com/aspnet/AspNetCore.Docs/issues/13614#issuecomment-542386663 comment and the [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1) article.

> Column Types:
Your demo - class text-left/right/center sometimes multiple occurs in the class tag but i cant reproduce when this happens.
> Own Project - TextAlignment="DataGridTextAlign.Center" dont work for DxDataGridCheckBoxColumn


Thank you for pointing this out. I created the [DataGrid for Blazor - Alignment classes are duplicated in rendered markup](https://supportcenter.devexpress.com/ticket/details/t857936/datagrid-for-blazor-alignment-classes-are-duplicated-in-rendered-markup) and [DataGrid for Blazor - CheckBox is not aligned in the center even if TextAlignment is set to "Center"](https://supportcenter.devexpress.com/ticket/details/t857968/datagrid-for-blazor-checkbox-is-not-aligned-in-the-center-even-if-textalignment-is-set)  reports regarding this.

**Comment by DanielReif** [comment] 2020-01-31 06:09
Hello @outsidergiant ,

sorry for that. I thought this was the most current version. I tryed to Update over Help -> Info but it appears "No update available". But on the homepage is the version 72.x.x. With this it work.

**Comment by SergeySeleznyov** [comment] 2020-02-07 16:25
Hi @DanielReif,

Happy to inform you that this issues are fixed in version [19.2.3](https://github.com/DevExpress/Blazor/releases/tag/v19.2.3).
Please feel free to reopen this issue should you have any difficulty.

**Closed by SergeySeleznyov** 2020-02-07 16:25 UTC
Labels: bug
