### ISSUE TITLE
NullReferenceException in DxDataGrid on selection

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#157] opened 2020-07-22 11:57 UTC
Hi!

I use a DevExpress virtual scrolling DataGrid and when I scroll and klick around, sooner or later I always get a NullReferenceException on row selection. I can't catch the exception either because it is not thrown in the MultipleSelectedDataRowsChanged event but somewhere in the DevExpress code.

The error message in the browser console always looks somewhat like this:
```
blazor.server.js:15 [2020-07-20T12:21:47.242Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at DevExpress.Blazor.Internal.Rx.ObservableBase`1.NotifySubscribers(T data)
   at DevExpress.Blazor.Internal.Grid.DataGridSelectionService`1.SetRowSelectedCore(T dataItem, Boolean value, DataGridSelectionMode mode, Boolean raiseChangedEvent)
   at DevExpress.Blazor.Internal.Grid.DataGridSelectionService`1.<>c__DisplayClass129_0.<IsRowSelectedInternal>b__2(Boolean newValue)
   at DevExpress.Blazor.Internal.Rx.ObservableBase`1.NotifySubscribers(T data)
   at DevExpress.Blazor.Internal.Grid.DataColumnModelBase`2.OnDataCellClick(T dataItem, MouseEventArgs args)
   at DevExpress.Blazor.Internal.Grid.DataColumnModelBase`2.<>c__DisplayClass100_0.<CreateDataCell>b__0(MouseEventArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I was able to reproduce it with this simple example, although it took much longer than in my real application:
[BlazorApp1.zip](https://github.com/DevExpress/Blazor/files/4959765/BlazorApp1.zip)
![2020-07-22 11_46_47-Window](https://user-images.githubusercontent.com/8930481/88173500-f7688d00-cc22-11ea-9dba-b64072df0df4.png)

Do you have an idea what produces this error?

**Comment by zabelin-vladimir** [comment] 2020-07-24 15:17
Hello @rysep2

I tried to reproduce the described issue with your sample but without success. Would you please send me a simple video illustrating how to reproduce it step by step?
Also, you mentioned that you use v20.1.4 of our controls. I recommend you update our controls to v20.1.5 and check if this issue is reproduced.

**Comment by zabelin-vladimir** [comment] 2020-10-02 15:18
Hello @rysep2

We didn't get any reply regarding this issue.

We are going to address technical requests only in our Support Center. So, if you still need our assistance with this issue, please create a new ticket in our [Support Center](https://www.devexpress.com/ask) and share the requested information with us.

We will be happy to assist you with any questions regarding our product.

**Comment by zabelin-vladimir** [comment] 2020-10-06 08:10
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova

**Closed by zabelin-vladimir** 2020-10-06 08:10 UTC
Labels: question
