### ISSUE TITLE
DxDataGrid Edit form closes suddenly

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#159] opened 2020-07-27 14:33 UTC
Hi DevExpress Team,

Today I came across a weird issue. I'd like to describe the steps that lead to the issue.

1. Have a `DxDataGrid` with `DetailRowTemplate` set to another `DxDataGrid` to load child records (master-detail)
2. Use a custom command button inside  `DxDataGridCommandColumn` in the child grid:
```
<DxDataGridCommandColumn Width="100px" EditButtonVisible="true" DeleteButtonVisible="false">
                                            <CellTemplate Context="ItemContext">
                                                @{
                                                    var id = (ItemContext as CouponTransaction).ID;
                                                }
                                                <button class="btn btn-link  mr-1"
                                                        @onclick="@(async() => await _detailGrid.StartRowEdit(ItemContext) )">
                                                    <i class="fa fa-pencil-alt fa-fw"></i>
                                                </button>
                                            </CellTemplate>
                                        </DxDataGridCommandColumn>
```
4. Use custom `EditFormTemplate` in the child grid
5. When clicking edit button the edit form of the child grids shows but suddenly disappears.

This issue doesn't occur when using the built-in grid edit command:

`<DxDataGridCommandColumn Width="100px" EditButtonVisible="true" DeleteButtonVisible="false" />`
However, I'd like to customize the edit button though I used my own template.

**Comment by outsidergiant** [comment] 2020-07-27 15:01
Hello Sven,

Do you use DataAsync for binding? If so, this behavior can be related to the fact that your model's field does not have the [Key] attribute defined. We've discussed this in the context of the following thread:
[Blazor DxDataGrid StartRowEdit - EditForm is hidden just after showing](https://supportcenter.devexpress.com/ticket/details/t899660/blazor-dxdatagrid-startrowedit-editform-is-hidden-just-after-showing).
If your scenario is different, please send us a sample project where this behavior can be reproduced.

**Comment by sven5** [comment] 2020-07-28 06:57
Hi @outsidergiant 

Thanks for your reply. 
You're right - the behavior is exactly the same as mentioned in the ticket. 
However, I already defined the `[Key]` attribute in my model and is still doesn't work.

**Comment by sven5** [comment] 2020-07-28 07:46
One addition, I created a modified sample project on behalf of the sample in [this ticket](https://supportcenter.devexpress.com/ticket/details/t900420/datagrid-for-blazor-the-edit-form-is-immediately-closed-on-a-custom-button-click-if-no).
I already answered there and uploaded my modified sample project.

**Comment by outsidergiant** [comment] 2020-07-28 14:33
Hi,

Thank you for posting your comment there. I created the [T918236](https://supportcenter.devexpress.com/ticket/details/t918236/datagrid-for-blazor-master-detail-the-edit-form-is-immediately-closed-on-a-custom-button) ticket on your behalf. Let's continue the conversation there.

**Comment by zabelin-vladimir** [comment] 2020-10-02 15:18
Hello @sven5 

As far as I understand from the following thread, this issue is resolved: [Custom edit button no longer working with v20.1.6](https://supportcenter.devexpress.com/ticket/details/t930239/custom-edit-button-no-longer-working-with-v20-1-6). 

We are going to address technical requests only in our Support Center. So, if you have any additional questions regarding this issue, or if you have any other questions about our component, feel free to contact us in our [Support Center](https://www.devexpress.com/ask). We will be happy to assist you with any questions regarding our product!

**Comment by zabelin-vladimir** [comment] 2020-10-06 08:10
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova

**Closed by zabelin-vladimir** 2020-10-06 08:10 UTC
Labels: bug
