### ISSUE TITLE
DxDataGrid: pre-sorting of DataSource not taken into account

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#19] opened 2019-07-02 14:05 UTC
Hi DevExpress team,

I came across a weird issue and I'm always sure that it worked in the past. I guess after upgrading to 0.10 or 0.11 the pre-sorting of dataSource is broken.
Please see the following example of sample data that is sorted:

```csharp
      public IEnumerable<OverviewEntry> Data { get; set; } = (new List<OverviewEntry> {
            new OverviewEntry
            {
                Id = Guid.NewGuid(),
                StoreName = "nedds Asch 01 (3)"
            },
            new OverviewEntry
            {
                Id = Guid.NewGuid(),
                StoreName = "nedds Asch St. (4)"
            },
            new OverviewEntry
            {
                Id = Guid.NewGuid(),
                StoreName = "nedds Aal St. (1)"
            },
            new OverviewEntry
            {
                Id = Guid.NewGuid(),
                StoreName = "nedds Ans St. (2)"
            }
        }).OrderBy(s => s.StoreName);
```

However, when binding to the grid the data is randomly displayed without sorting (press multiple times F5). 
I expect that the grid preserves the order of items (order in brackets at the end of StoreName).  

One has to click on the column header to get the sorting. Is there any programmatic way to set a solumn's sorting? 

Thanks
Sven

**Comment by SergeySeleznyov** [comment] 2019-07-03 13:46
Hi Sven,
 
I am concerned to hear that you have difficulty using the components.
I've created a following razor file trying to reproduce the issue:

```
@page "/Issue19"

@if (Data == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <DxDataGrid Data=@Data>

        <DxDataGridCommandColumn></DxDataGridCommandColumn>

        <DxDataGridColumn Field="Id" Caption="Id">
        </DxDataGridColumn>
        <DxDataGridColumn Field="StoreName" Caption="StoreName">
        </DxDataGridColumn>

    </DxDataGrid>
}

@functions {
    public class OverviewEntry{
        public Guid Id { get; set; }
        public string StoreName  { get; set; }
    }
    public IEnumerable<OverviewEntry> Data { get; set; } = (new List<OverviewEntry> {
        new OverviewEntry
        {
            Id = Guid.NewGuid(),
            StoreName = "nedds Asch 01 (3)"
        },
        new OverviewEntry
        {
            Id = Guid.NewGuid(),
            StoreName = "nedds Asch St. (4)"
        },
        new OverviewEntry
        {
            Id = Guid.NewGuid(),
            StoreName = "nedds Aal St. (1)"
        },
        new OverviewEntry
        {
            Id = Guid.NewGuid(),
            StoreName = "nedds Ans St. (2)"
        }
    }).OrderBy(s => s.StoreName);
}

```

Pressing F5 refreshes Guid, but not StoreName.

![image](https://user-images.githubusercontent.com/950357/60596596-07ac9080-9db2-11e9-9c8d-feaa30aaa13b.png)
![image](https://user-images.githubusercontent.com/950357/60596613-0f6c3500-9db2-11e9-9611-f7aafb26f14d.png)

The Grid looks sorted by StoreName and rows do not change their places.
It looks like I missed an important step to reproduce this issue. Would you please try to find the difference between my example and your application?

**Comment by sven5** [comment] 2019-07-04 07:05
@SergeySeleznyov 
Thanks for your reply. I finally found the issue, there's nothing wrong with `DxDataGrid` at all. I had an issue with my model class regarding `IComparable`.
Sorry for wasting your time.

Regards
Sven

**Comment by SergeySeleznyov** [comment] 2019-07-04 10:47
Sven,
 
Happy to hear that the issue is gone.
Feel free to contact us, we are happy to help.

**Comment by sven5** [comment] 2019-07-04 13:51
@SergeySeleznyov 

Sorry I have to reopen this case. I still wasn't able to get the correct sorting.
Please modify your example code and add the `KeyAttribute` to the Id:
```csharp
 public class OverviewEntry{
        [Key]
        public Guid Id { get; set; }
        public string StoreName  { get; set; }
    }

```

Now the grid automatically sorts by the Id column and not the Name - and that's really weird.

Regards
Sven

**Comment by sven5** [comment] 2019-07-04 14:28
One addition: It appears that also adding the property `KeyFieldName` leads to the sorting specified there and the initial sorting is ignored. It seems there is something wrong with the data-binding logic.

**Comment by SergeySeleznyov** [comment] 2019-07-04 17:14
Sven,

I have reproduced this issue on both 0.0.11 and 0.0.10, I label it as bug and will fix it.

Thank you very much for you time!

**Comment by SergeySeleznyov** [comment] 2019-07-08 11:17
Hi Sven,

Thank you for your patience.
This behavior is a part of the DevExtreme.AspNet.Data project. They have some additional API for default item sorting.
 
We have several options to use this API in DxDataGrid:
1. Set default sorting for Column. The sorting order will be indicated in the Column Header.
2. The DefaultSorting API in the root of DxDataGrid. You can specify the field to sort and the sorting order. The default sorting will not be indicated in the Column Header.
 

Could you clarify which of these ways is more preferable for your project?
 
Should you have any questions about the DevExtreme.AspNet.Data logic, feel free to ask on the [project github page](https://github.com/DevExpress/DevExtreme.AspNet.Data).

Thank you!

**Comment by sven5** [comment] 2019-07-09 08:27
Hi @SergeySeleznyov 

Thanks for your update.
Currently, the first way is sufficient for my needs. However, the 2nd way would be the more flexible one. But please keep it simple and choose the one that is easier to implement - I'm fine with any of those.

Regards
Sven

**Comment by SergeySeleznyov** [comment] 2019-07-09 09:32
Thank you very much Sven for your time and feedback!
I have put it into our backlog for future releases.

Regards
Sergey

**Closed by SergeySeleznyov** 2019-07-09 09:32 UTC
Labels: bug

**Comment by sven5** [comment] 2019-07-22 09:00
Hi @SergeySeleznyov,

Could you please elaborate if this issue is already fixed?
Today I updated to 0.12 and it seems that this problem no longer exists.

Thanks
Sven

**Comment by SergeySeleznyov** [comment] 2019-07-22 10:19
Hi Sven,

I have checked our 0.12 version, our latest sources and the latest version of the DevExtreme.AspNet.Data project.
All of them return data in a random order.

I've closed this issue because this behavior is considered to be "by design" in the DevExtreme.AspNet.Data project. There is a property to define default sorting in the DevExtreme.AspNet.Data project. So, we'll be required to support this feature in Blazor components. We have not implemented it yet.

This feature is in our backlog list. It is up to you to reopen this issue. In this case, we will keep it opened until we support the default sorting API.

Thank you for your interest in our product.

Regards
Sergey

**Comment by sven5** [comment] 2019-07-22 10:50
@SergeySeleznyov 

Thanks for clarification.

Regards
Sven

**Comment by SergeySeleznyov** [comment] 2019-08-16 11:47
Hello @sven5  ,
 
We have implemented the feature you asked. Here is an API that will allow you to manage column sorting programmatically:
 
[Demo](https://demos.devexpress.com/blazor/GridSortData)

> SortOrder - Specifies a column sort order.
> SortIndex - Specifies a column position among sorted columns.

**Comment by sven5** [comment] 2019-08-16 12:12
Hi @SergeySeleznyov 

This is great news. As always I'm very excited of the evolution of  your products. Since yesterday I've been waiting for your update to support preview 8 and - suprise - you haven't let me down with that. :smirk: 

Thanks Sergey!
Have a nice weekend.
