### ISSUE TITLE
DxComboBox not working in Safari

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#156] opened 2020-07-20 11:10 UTC
Hi support team,

my customer informed me about a problem that the DxComboBox doesn'topen on his iPad.
Could you please look into this?

device info:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

Thanks
Sven

**Comment by outsidergiant** [comment] 2020-07-20 12:42
[https://github.com/DevExpress/Blazor/issues/156](https://github.com/DevExpress/Blazor/issues/156)

Hello Sven,

We tested our ComboBox on different devices and were not able to reproduce the issue. Ask your client to update iOS to v13.6.1 to check if this issue is reproduced there.
In the device information that you sent, the Mac OS is mentioned so we tested our ComboBox there but still no issue was reproduced. It also works with the enabled and disabled Desktop Mode.

**Comment by sven5** [comment] 2020-07-20 12:44
@outsidergiant  Ok thank you very much. I will ask my customer to update the device.

**Comment by sven5** [comment] 2020-07-20 12:50
My client is using v13.5.1 and 13.2.3 - they tested on both devices and the combobox does not open.

**Comment by sven5** [comment] 2020-07-21 07:34
We updated devices manually to v13.6.1 - automatic update didn't offer this update. 
However I think this is far too limited. Is there any special reason why we need this very new update to get `DxComboBox `working?

Thanks for your understanding.

**Comment by outsidergiant** [comment] 2020-07-21 12:39
Hello Sven,

Without reproducing the issue locally, it's hard to say precisely what may cause it. But if the issue relates to Blazor in general, we also suggest you update to a new version since we support the latest browser and OS versions like Microsoft:
[Supported Browsers](https://docs.devexpress.com/Blazor/401588/common-concepts/supported-browsers).
[ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1).

See [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/13614#issuecomment-542386663).

If the issue relates to our component's or a project's configuration, feel free to send it to us for research. To ensure the privacy of your project, submit a ticket in our [Support Center](https://supportcenter.devexpress.com/ticket/create).

**Comment by zabelin-vladimir** [comment] 2020-10-06 08:10
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova

**Closed by zabelin-vladimir** 2020-10-06 08:10 UTC
